### ISSUE TITLE
Doesn't work on archlinux

### ISSUE THREAD

**Issue by beenotung** [ranisalt/netmon#1]
Installed via yaourt (aur/netmon-git 0.r12.9b6a452-1)
Below error happens when running with/without '--help' argument
```
Failed to connect to non-global ctrl_ifname: (nil)  error: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/netmon", line 114, in <module>
    MainApp()
  File "/usr/bin/netmon", line 77, in __init__
    self.update_icon()
  File "/usr/bin/netmon", line 108, in update_icon
    tooltip = self.get_tooltip(info['interface'], info['connected'])
  File "/usr/bin/netmon", line 99, in get_tooltip
    res = '\n'.join([res, wpa_status()])
  File "/usr/bin/netmon", line 49, in wpa_status
    return subprocess.check_output(['wpa_cli', 'status']).strip()
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['wpa_cli', 'status']' returned non-zero exit status 255
```

**Comment by ranisalt** [comment]
This is not the repository for the AUR package netmon-git. The correct one is https://github.com/chmduquesne/netmon, but it's as good as dead now.
